adm/urls.py
from django.urls import path
from . import views

app_name='adm'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('envia_email', views.envia_email, name='envia_email'),
    path('envia/<int:id>', views.envia, name='envia'),
    path('relacao_candidatos', views.relacao_candidatos, name='relacao_candidatos'),
    path('relacao_candidatos_assinatura', views.relacao_candidatos_assinatura, name='relacao_candidatos_assinatura'),
    path('relacao_candidatos_porta', views.relacao_candidatos_porta, name='relacao_candidatos_porta'),
    path('sair', views.sair, name='sair'),
]

enfermagem/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Escola de Enfermagem'
admin.site.site_title = 'Escola de Enfermagem'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('selecao.urls', namespace='selecao')),
    path('adm/', include('adm.urls', namespace='adm')),
    path('accounts/', include('django.contrib.auth.urls')),
]

selecao/urls.py
from django.urls import path
from . import views

app_name='selecao'

urlpatterns = [
    path('inicio_teste', views.inicio_teste, name='inicio_teste'),
    #
    path('', views.inicio, name='inicio'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('imprime/<str:chave>', views.imprime, name='imprime'),
    path('consulta', views.consulta, name='consulta'),
    path('consulta_chave/<str:chave>', views.consulta_chave, name='consulta_chave'),
    path('cadastro_corrige/<str:chave>', views.cadastro_corrige, name='cadastro_corrige'),
    path('contato', views.contato, name='contato'),
    path('alocacao', views.alocacao, name='alocacao'),
    path('divulga', views.divulga, name='divulga'),
    path('confirmacao/<str:chave>', views.confirmacao, name='confirmacao'),
    #
#    path('corrige_nome', views.corrige_nome, name='corrige_nome'),
]

selecao/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import *
from .functions import validate_CPF

class ConsultaForm(forms.Form):
    cpf = forms.CharField(label='CPF', max_length=14, widget = forms.TextInput(attrs={'onkeydown':"mascara(this,icpf)"}))

    def clean_cpf(self):
        cpf = validate_CPF(self.cleaned_data["cpf"])
        return cpf


class CandidatoForm(ModelForm):
    DEFICIENCIA = (
        ('S', 'Sim'),
        ('N', 'Não'),
    )

    cpf = forms.CharField(label='CPF', max_length=14, widget = forms.TextInput(attrs={'onkeydown':"mascara(this,icpf)"}))
    celular = forms.CharField(label= "Celular", max_length=15, widget = forms.TextInput(attrs={'onkeydown':"mascara(this,icelular)", 'onload' : 'mascara(this,icelular)'}))
    tel = forms.CharField(label = "Telefone",required=False, max_length=14, widget = forms.TextInput(attrs={'onkeydown':"mascara(this,itelefone)", 'onload' : 'mascara(this,itelefone)'}))
    dt_nascimento = forms.DateField(label='Dt. Nascimento:', widget=forms.SelectDateWidget(years=range(1900, 2010)))

#    deficiencia = forms.CharField(widget=forms.RadioSelect(choices=DEFICIENCIA))
    deficiencia = forms.ChoiceField(label='Possui deficiência?',widget=forms.RadioSelect, choices=DEFICIENCIA)
    qual_deficiencia = forms.CharField(label='Indique qual a deficiência:',required=False,max_length=200,widget=forms.Textarea(attrs={'size': '40'}))
    necessidade = forms.CharField(label='Informe se necessita de alguma condição especial para a realização da prova:',required=False,max_length=200,widget=forms.Textarea(attrs={'size': '40'}))

    class Meta:
        model = Candidato
        exclude = ['chave', 'ip', 'dt_inclusao']

    def clean_cpf(self):
        cpf = validate_CPF(self.cleaned_data["cpf"])
        return cpf

    def clean_celular(self):
        telefone = self.cleaned_data["celular"]
        telefone = telefone.replace("(",'')
        telefone = telefone.replace(")",'')
        telefone = telefone.replace("-",'')
        telefone = telefone.replace(" ",'')
        if len(telefone) == 10:
            if telefone[2:3] != '2':
                raise ValidationError('Insira um número válido ')
        else:
            if len(telefone) != 11:
                raise ValidationError('Insira um número válido ')
        return telefone
    
    def clean_tel(self):
        telefone = self.cleaned_data["tel"]
        telefone = telefone.replace("(",'')
        telefone = telefone.replace(")",'')
        telefone = telefone.replace("-",'')
        telefone = telefone.replace(" ",'')
        if len(telefone) != 10 and len(telefone) != 0:
            raise ValidationError('Insira um número válido')        
        return telefone
    
    def clean_email(self):
        email = self.cleaned_data["email"]

        if email.find('@') == -1:
            raise ValidationError('Insira um e-mail válido')        

        return email


    def clean_deficiencia(self):
        if self.cleaned_data["deficiencia"] == 'S':
            self.fields['qual_deficiencia'].widget.attrs['readonly'] = False
            self.fields['necessidade'].widget.attrs['readonly'] = False
        else:
            self.fields['qual_deficiencia'].widget.attrs['readonly'] = True
            self.fields['necessidade'].widget.attrs['readonly'] = True

        return self.cleaned_data["deficiencia"]


class ContatoForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=60)
    cpf = forms.CharField(label='CPF', max_length=14, widget = forms.TextInput(attrs={'onkeydown':"mascara(this,icpf)"}))
    celular = forms.CharField(label= "Celular", max_length=15, widget = forms.TextInput(attrs={'onkeydown':"mascara(this,icelular)", 'onload' : 'mascara(this,icelular)'}))
    email = forms.CharField(label='E-Mail', max_length=200)
    duvida = forms.CharField(label='Dúvida',max_length=1000,widget=forms.Textarea(attrs={'size': '40'}))

    def clean_cpf(self):
        cpf = validate_CPF(self.cleaned_data["cpf"])
        return cpf

    def clean_celular(self):
        telefone = self.cleaned_data["celular"]
        telefone = telefone.replace("(",'')
        telefone = telefone.replace(")",'')
        telefone = telefone.replace("-",'')
        telefone = telefone.replace(" ",'')
        if len(telefone) == 10:
            if telefone[2:3] != '2':
                raise ValidationError('Insira um número válido ')
        else:
            if len(telefone) != 11:
                raise ValidationError('Insira um número válido ')
        return telefone

selecao/views.py
from django.core.checks.messages import Error
from django.shortcuts import render, redirect
from .forms import *
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def inicio_teste(request):
    return render(request, 'inicio.html')


def inicio(request):
    from datetime import date, datetime

    hoje = date.today()
    data_inicio = datetime.strptime('11/10/2021', '%d/%m/%Y').date()
    data_fim = datetime.strptime('15/10/2021', '%d/%m/%Y').date()

    data_resultado = datetime.strptime('08/12/2021', '%d/%m/%Y').date()

    if hoje >= data_resultado:
        return render(request, 'inicio_resultado.html')

    if hoje >= data_inicio and hoje <= data_fim:
        return render(request, 'inicio.html')

    return render(request, 'inicio_aguardar.html')


def cadastro(request):
    from django.template import Context
    from django.template.loader import render_to_string, get_template
    from django.core.mail import EmailMessage
    import uuid
    from ipware import get_client_ip

    if request.method == 'POST':
        form = CandidatoForm(request.POST)

        if form.is_valid():
            cadastro = form.save(commit=False)

            chave = str(uuid.uuid4())
            cadastro.chave = chave

            # Busca IP

            client_ip, is_routable = get_client_ip(request)
            if client_ip is None:
                # Unable to get the client's IP address
                print(client_ip)
                client_ip = '0.0.0.0'
            else:
                # We got the client's IP address
                if is_routable:
                    print('sim:', is_routable)
                    # The client's IP address is publicly routable on the Internet
                else:
                    print('não:', is_routable)
                    # The client's IP address is privat

            cadastro.ip = client_ip

            cadastro.save()

            # Envia e-mail

            dados = {
                'id': cadastro.id,
                'nome': cadastro.nome,
                'dt_nascimento': cadastro.dt_nascimento,
                'cpf': cadastro.cpf,
                'celular': cadastro.celular,
                'tel': cadastro.tel,
                'email': cadastro.email,
                'deficiencia': cadastro.deficiencia,
                'qual_deficiencia': cadastro.qual_deficiencia,
                'necessidade': cadastro.necessidade,
                'dt_inclusao': cadastro.dt_inclusao,
                'ip': cadastro.ip,
            }

            mensagem = get_template('mail.html').render(dados)

            msg = EmailMessage(
                'Confirmação de Inscrição do Processo Seletivo para Curso de Técnico em Enfermagem',
                mensagem,
                'Escola de Auxiliares e Técnicos de Enfermagem Nossa Senhora de Fátima - Inscrição <inscricao@sme.novafriburgo.rj.gov.br>',
                [cadastro.email],
            )
            msg.content_subtype = "html"  # Main content is now text/html
            msg.send()

            return render(request, 'cadastrook.html', { 'chave': chave })

        else:
            # Se teve erro:
            print('Erro: ', form.errors)
            erro_tmp = str(form.errors)
            erro_tmp = erro_tmp.replace('<ul class="errorlist">', '')
            erro_tmp = erro_tmp.replace('</li>', '')
            erro_tmp = erro_tmp.replace('<ul>', '')
            erro_tmp = erro_tmp.replace('</ul>', '')
            erro_tmp = erro_tmp.split('<li>')

            messages.error(request, erro_tmp[2])

    else:
        form = CandidatoForm()

    return render(request, 'cadastro.html', { 'form': form })


def imprime(request, chave):
    candidato = Candidato.objects.get(chave=chave)

    return render(request, 'ficha.html', { 'candidato': candidato })


def consulta(request):
    from django.template import Context
    from django.template.loader import render_to_string, get_template
    from django.core.mail import EmailMessage
    import uuid

    if request.method == 'POST':
        form = ConsultaForm(request.POST)

        if form.is_valid():

            cpf = form.cleaned_data['cpf']

            try:
                candidato = Candidato.objects.get(cpf=cpf)
            except ObjectDoesNotExist:
                messages.error(request, 'CPF não cadastrado.')
                return render(request, 'consulta.html', { 'form': form })

            # Envia e-mail

            dados = {
                'id': candidato.id,
                'nome': candidato.nome,
                'cpf': candidato.cpf,
                'email': candidato.email,
                'dt_inclusao': candidato.dt_inclusao,
                'ip': candidato.ip,
                'chave': candidato.chave,
            }

            mensagem = get_template('mail_consulta.html').render(dados)

            msg = EmailMessage(
                'Consulta a inscrição do Processo Seletivo para Curso de Técnico em Enfermagem',
                mensagem,
                'Escola de Auxiliares e Técnicos de Enfermagem Nossa Senhora de Fátima - Inscrição <inscricao@sme.novafriburgo.rj.gov.br>',
                [candidato.email],
            )
            msg.content_subtype = "html"  # Main content is now text/html
            msg.send()


            messages.error(request, 'Enviamos um e-mail para o endereço informado, que dará acesso ao cadastro.')

            return redirect ('/')

        else:
            # Se teve erro:
            print('Erro: ', form.errors)
            erro_tmp = str(form.errors)
            erro_tmp = erro_tmp.replace('<ul class="errorlist">', '')
            erro_tmp = erro_tmp.replace('</li>', '')
            erro_tmp = erro_tmp.replace('<ul>', '')
            erro_tmp = erro_tmp.replace('</ul>', '')
            erro_tmp = erro_tmp.split('<li>')

            messages.error(request, erro_tmp[2])

    else:
        form = ConsultaForm()

    return render(request, 'consulta.html', { 'form': form })


def consulta_chave(request, chave):

    try:
        candidato = Candidato.objects.get(chave=chave)
    except ObjectDoesNotExist:
        messages.error(request, 'Chave não cadastrada.')
        return redirect ('/consulta')

    return render(request, 'cadastro_mostra.html', { 'candidato': candidato })



def cadastro_corrige(request, chave):
    from django.template import Context
    from django.template.loader import render_to_string, get_template
    from django.core.mail import EmailMessage
    import uuid
    from ipware import get_client_ip

    try:
        candidato = Candidato.objects.get(chave=chave)
    except ObjectDoesNotExist:
        messages.error(request, 'Chave não cadastrada.')
        return redirect ('/consulta')


    if request.method == 'POST':
        form = CandidatoForm(request.POST, instance=candidato)

        if form.is_valid():
            cadastro = form.save(commit=False)

            chave = str(uuid.uuid4())
            cadastro.chave = chave

            # Busca IP

            client_ip, is_routable = get_client_ip(request)
            if client_ip is None:
                # Unable to get the client's IP address
                print(client_ip)
                client_ip = '0.0.0.0'
            else:
                # We got the client's IP address
                if is_routable:
                    print('sim:', is_routable)
                    # The client's IP address is publicly routable on the Internet
                else:
                    print('não:', is_routable)
                    # The client's IP address is privat

            cadastro.ip = client_ip

            cadastro.save()

            # Envia e-mail

            dados = {
                'id': cadastro.id,
                'nome': cadastro.nome,
                'dt_nascimento': cadastro.dt_nascimento,
                'cpf': cadastro.cpf,
                'celular': cadastro.celular,
                'tel': cadastro.tel,
                'email': cadastro.email,
                'deficiencia': cadastro.deficiencia,
                'qual_deficiencia': cadastro.qual_deficiencia,
                'necessidade': cadastro.necessidade,
                'dt_inclusao': cadastro.dt_inclusao,
                'ip': cadastro.ip,
            }

            mensagem = get_template('mail.html').render(dados)

            msg = EmailMessage(
                'Correção da inscrição do Processo Seletivo para Curso de Técnico em Enfermagem',
                mensagem,
                'Escola de Auxiliares e Técnicos de Enfermagem Nossa Senhora de Fátima - Inscrição <inscricao@sme.novafriburgo.rj.gov.br>',
                [cadastro.email],
            )
            msg.content_subtype = "html"  # Main content is now text/html
            msg.send()

            return render(request, 'cadastrook.html', { 'chave': chave })

        else:
            # Se teve erro:
            print('Erro: ', form.errors)
            erro_tmp = str(form.errors)
            erro_tmp = erro_tmp.replace('<ul class="errorlist">', '')
            erro_tmp = erro_tmp.replace('</li>', '')
            erro_tmp = erro_tmp.replace('<ul>', '')
            erro_tmp = erro_tmp.replace('</ul>', '')
            erro_tmp = erro_tmp.split('<li>')

            messages.error(request, erro_tmp[2])

    else:
        form = CandidatoForm(instance=candidato)

    return render(request, 'cadastro.html', { 'form': form })


def contato(request):
    from django.template import Context
    from django.template.loader import render_to_string, get_template
    from django.core.mail import EmailMessage

    if request.method == 'POST':
        form = ContatoForm(request.POST)

        if form.is_valid():

            # Envia e-mail

            dados = {
                'nome': form.cleaned_data['nome'],
                'cpf': form.cleaned_data['cpf'],
                'celular': form.cleaned_data['celular'],

selecao/templates/cadastro_mostra.html
{% extends "cab.html" %}

{% load template_filters %}

{% load static %}

{% block cab %}
<br>
<div class="container">

    <div class="row">
        <div class="col">
            <h3>Informações:</h3>
        </div>

        <div class="col text-right">
            <a href="{% url 'selecao:inicio' %}" class="btn btn-primary" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Volta
            </a>
        </div>
    </div>

    <h5>Caso queira imprimir o protocolo de inscrição, clique <a href="{% url 'selecao:imprime' candidato.chave %}" target="_blank"><span style="cursor:pointer;text-decoration:underline;color:#0000ff;">AQUI.</span></a></h5>

    <br>

    <div class="col">
        <h3>Cadastro:</h3>
    </div>


    <table  class="table table-striped table-bordered">

        <tr>
            <th>Inscrição N°</th>
            <td>{{ candidato.id }}</td>
        </tr>
        <tr>
            <th>Nome:</th>
            <td>{{ candidato.nome }}</td>
        </tr>
        <tr>
            <th>Data Nascimento:</th>
            <td>{{ candidato.dt_nascimento | date:"SHORT_DATE_FORMAT" }}</td>
        </tr>
        <tr>
            <th>CPF:</th>
            <td>{{ candidato.cpf | formata_cpf }}</td>
        </tr>
        <tr>
            <th>Celular:</th>
            <td>{{ candidato.celular | formata_tel }}</td>
        </tr>
        <tr>
            <th>Telefone:</th>
            <td>{{ candidato.tel | formata_tel }}</td>
        </tr>
        <tr>
            <th>E-Mail:</th>
            <td>{{ candidato.email }}</td>
        </tr>
        <tr>
            <th>Possui deficiência?</th>
            <td>{% if candidato.deficiencia == 'S' %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <th>Indique qual deficiência?</th>
            <td>{{ candidato.qual_deficiencia }}</td>
        </tr>
        <tr>
            <th>Informe se necessita de alguma condição especial para a realização da prova:</th>
            <td>{{ candidato.necessidade }}</td>
        </tr>
        <tr>
            <th>Data Cadastro:</th>
            <td>{{ candidato.dt_inclusao | date:"SHORT_DATETIME_FORMAT" }}</td>
        </tr>
        <tr>
            <th>IP:</th>
            <td>{{ candidato.ip }}</td>
        </tr>

    </table>

    <a href="{% url 'selecao:cadastro_corrige' candidato.chave %}" class="btn btn-primary" role="button">Corrigir informações</a>


</div>

<SCRIPT LANGUAGE="JavaScript">

    function leech(v){
        v=v.replace(/o/gi,"0")
        v=v.replace(/i/gi,"1")
        v=v.replace(/z/gi,"2")
        v=v.replace(/e/gi,"3")
        v=v.replace(/a/gi,"4")
        v=v.replace(/s/gi,"5")
        v=v.replace(/t/gi,"7")
        return v
    }

    function open_popup(url){
        newwindow = window.open(url,'{{title}}', 'height = 400,width = 600');
        if(window.focus) {newwindow.focus()}
        return false;
    }

    function data(v){
        v=v.replace(/\D/g,"")                //Remove tudo o que nao e digito
        v=v.replace(/(\d{2})(\d)/,"$1/$2")   //Coloca um ponto entre o terceiro e o quarto digitos
        v=v.replace(/(\d{2})(\d)/,"$1/$2")   //Coloca um ponto entre o terceiro e o quarto digitos
                                                //de novo (para o segundo bloco de numeros)
        return v
    }
    function icpf(v){
        v=v.replace(/\D/g,"")                    //Remove tudo o que nao e digito
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o terceiro e o quarto digitos
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o terceiro e o quarto digitos
                                                //de novo (para o segundo bloco de numeros)
        v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2") //Coloca um hifen entre o terceiro e o quarto digitos
        return v
    }
    function itelefone(v){
        v=v.replace(/\D/g,"")                 //Remove tudo o que nao e digito
        v=v.replace(/^(\d\d)(\d)/g,"($1) $2") //Coloca parenteses em volta dos dois primeiros digitos
        v=v.replace(/(\d{4})(\d)/,"$1-$2")    //Coloca hifen entre o quarto e o quinto digitos
        return v
    }
    function icep(v){
        v=v.replace(/\D/g,"")                 //Remove tudo o que nao e digito
        v=v.replace(/(\d{2})(\d)/,"$1.$2")    //Coloca hifen entre o quarto e o quinto digitos
        v=v.replace(/(\d{3})(\d)/,"$1-$2")    //Coloca hifen entre o quarto e o quinto digitos
        return v
    }
    function icelular(v){
        v=v.replace(/\D/g,"")                 //Remove tudo o que nao e digito
        v=v.replace(/^(\d\d)(\d)/g,"($1) $2") //Coloca parenteses em volta dos dois primeiros digitos
        v=v.replace(/(\d{5})(\d)/,"$1-$2")    //Coloca hifen entre o quarto e o quinto digitos
        return v
    }
    function mascara(o,f){
        v_obj=o
        v_fun=f
        setTimeout("execmascara()",1)
    }

    function execmascara(){
        v_obj.value=v_fun(v_obj.value)
    }

</script>

{% endblock %}

selecao/templates/consulta.html
{% extends "cab.html" %}

{% load static %}

{% block cab %}
<br>
<div class="container">

    <div class="row">
        <div class="col">
            <h3>Consulta:</h3>
        </div>

        <div class="col text-right">
            <a href="{% url 'selecao:inicio' %}" class="btn btn-primary" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
                Volta
            </a>
        </div>
    </div>

    <br>

    <form method="POST" id="formulario">

        {% csrf_token %}
        <table  class="table table-striped table-bordered">
            {{ form.as_table }}
        </table>

        <input class="btn btn-primary" type="submit" value="Consultar">
    </form>

</div>

<SCRIPT LANGUAGE="JavaScript">

    function leech(v){
        v=v.replace(/o/gi,"0")
        v=v.replace(/i/gi,"1")
        v=v.replace(/z/gi,"2")
        v=v.replace(/e/gi,"3")
        v=v.replace(/a/gi,"4")
        v=v.replace(/s/gi,"5")
        v=v.replace(/t/gi,"7")
        return v
    }

    function open_popup(url){
        newwindow = window.open(url,'{{title}}', 'height = 400,width = 600');
        if(window.focus) {newwindow.focus()}
        return false;
    }

    function icpf(v){
        v=v.replace(/\D/g,"")                    //Remove tudo o que nao e digito
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o terceiro e o quarto digitos
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o terceiro e o quarto digitos
                                                //de novo (para o segundo bloco de numeros)
        v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2") //Coloca um hifen entre o terceiro e o quarto digitos
        return v
    }
    function mascara(o,f){
        v_obj=o
        v_fun=f
        setTimeout("execmascara()",1)
    }

    function execmascara(){
        v_obj.value=v_fun(v_obj.value)
    }

</script>

{% endblock %}

selecao/templates/inicio.html
{% extends "cab.html" %}

{% load static %}

{% block cab %}
<br>
<div class="container">

    <div class="row">
        <div class="col">
            <h3>Informações:</h3>
        </div>
    </div>
    <ul>
    <li>O Período de inscrições para o Processo Seletivo para o Curso de Técnico em Enfermagem é de 11/10/2021 a 15/10/2021;</li>
    <li>Um e-mail de Confirmação de Inscrição será enviado imediatamente para o endereço informado assim que a inscrição for concluída;</li>
    <li>O Processo Seletivo será realizado no dia 31 de outubro de 2021;</li>
    <li>O candidato deverá acompanhar este site, bem como o e-mail cadastrado, pois poderemos divulgar informações por estes canais;</li>
    <li>O local e o horário do Processo Seletivo será divulgado no dia 19 de outubro de 2021, no Diário Oficial do Município, através do site da Prefeitura Municipal de Nova Friburgo;</li>
    <li>Para maiores informações, leia o Edital e a Corrigenda disponíveis acima.</li>
    <li>Em caso de dúvidas, entre em contato conosco clicando <a href="{% url 'selecao:contato' %}"><span style="cursor:pointer;text-decoration:underline;color:#0000ff;">AQUI.</span></a>.</li>
    </ul>
    <br>
    <a href="{% url 'selecao:cadastro' %}" class="btn btn-primary" role="button">
        Inscrição
    </a>

    <a href="{% url 'selecao:consulta' %}" class="btn btn-primary" role="button">
        Consultar Inscrição
    </a>

</div>

{% endblock %}

selecao/templates/inicio_aguardar.html
{% extends "cab.html" %}

{% load static %}

{% block cab %}
<br>
<div class="container">

    <div class="row">
        <div class="col">
            <h3>A inscrição ficou disponível entre os dias 11 e 15 de outubro de 2021.</h3>
            <ul>
                <li>Clique <a href="https://drive.google.com/file/d/1mhW8ULu2mOQoHXSaSR4yzj0AheqaKWQQ/view?usp=sharing" target="_blank"><span style="cursor:pointer;text-decoration:underline;color:#0000ff;">AQUI</span></a> para baixar informações sobre local e horário do processo seletivo.</li>
                <li>Em caso de dúvidas, entre em contato conosco clicando <a href="{% url 'selecao:contato' %}"><span style="cursor:pointer;text-decoration:underline;color:#0000ff;">AQUI.</span></a>.</li>
            </ul>
        </div>
    </div>

</div>

{% endblock %}

selecao/templates/mail_consulta.html
{% load template_filters %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Consulta a inscrição do Processo Seletivo para Curso de Técnico em Enfermagem</title>
        <style type="text/css">
            .titulo {
                float: left;
                font-weight: bold;
            }
            .numero {
                float: right;
            }
        </style>
    </head>

    <body>
        <div class="titulo">FICHA DE INSCRIÇÃO</div> <div class="numero">N° {{ id }}</div><br>
        <br>
        Nome: {{ nome }}<br>
        CPF: {{ cpf | formata_cpf }}<br>
        E-Mail: {{ email }}<br>
        Data Cadastro: {{ dt_inclusao | date:"SHORT_DATETIME_FORMAT" }} - 
        IP: {{ ip }}<br>
        <a href="https://enfermagem.pmnf.rj.gov.br/consulta_chave/{{ chave }}">Clique aqui para acessar o cadastro</a>
    </body>
</html>