adm/urls.py
from django.urls import path
from . import views

app_name='adm'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('envia_email', views.envia_email, name='envia_email'),
    path('envia/<int:id>', views.envia, name='envia'),
    path('relacao_candidatos', views.relacao_candidatos, name='relacao_candidatos'),
    path('relacao_candidatos_assinatura', views.relacao_candidatos_assinatura, name='relacao_candidatos_assinatura'),
    path('relacao_candidatos_porta', views.relacao_candidatos_porta, name='relacao_candidatos_porta'),
    path('sair', views.sair, name='sair'),
]

enfermagem/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Escola de Enfermagem'
admin.site.site_title = 'Escola de Enfermagem'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('selecao.urls', namespace='selecao')),
    path('adm/', include('adm.urls', namespace='adm')),
    path('accounts/', include('django.contrib.auth.urls')),
]

adm/models.py
from django.db import models

# Create your models here.

adm/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import *

class BuscaNomeForm(forms.Form):

    nome = forms.CharField()

adm/views.py
from django.shortcuts import render, redirect
from django.core.checks.messages import Error
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .forms import *

from selecao.models import Alocacao, Candidato

# Create your views here.

@login_required
def inicio(request):
    return render(request, 'adm/inicio.html')


@login_required
def sair(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/accounts/logout')
    else:
        return redirect('/accounts/login')

@login_required
def envia_email(request):

    if request.method == 'POST':
        form = BuscaNomeForm(request.POST)

        if form.is_valid():

            nome = form.cleaned_data['nome']

            candidatos = Candidato.objects.filter(nome__icontains=nome)

            if len(candidatos) == 0:
                messages.error(request, 'Nome não cadastrado.')
#                return render(request, "registro_beneficios_busca.html",{"form" : form, 'paroquia_atividade': paroquia_atividade })
            else:
                return render(request, "adm/envia_email.html",{'candidatos': candidatos })

        else:
            # Se teve erro:
            print('Erro: ', form.errors)
            erro_tmp = str(form.errors)
            erro_tmp = erro_tmp.replace('<ul class="errorlist">', '')
            erro_tmp = erro_tmp.replace('</li>', '')
            erro_tmp = erro_tmp.replace('<ul>', '')
            erro_tmp = erro_tmp.replace('</ul>', '')
            erro_tmp = erro_tmp.split('<li>')

            messages.error(request, erro_tmp[1] + ': ' + erro_tmp[2])

    form = BuscaNomeForm()

    return render(request, "adm/busca_nome.html",{"form" : form})


@login_required
def envia(request, id):
    from django.template import Context
    from django.template.loader import render_to_string, get_template
    from django.core.mail import EmailMessage

    candidato = Candidato.objects.get(id=id)

    alocacao = Alocacao.objects.get(candidato=candidato)

    # Envia e-mail

    dados = {
        'nome': alocacao.candidato.nome,
        'cpf': alocacao.candidato.cpf,
        'email': alocacao.candidato.email,
        'sala': alocacao.sala.sala,
        'horario': alocacao.sala.horario.horario,
        'local': alocacao.sala.horario.local.nome,
        'rua': alocacao.sala.horario.local.rua,
        'numero': alocacao.sala.horario.local.numero,
        'bairro': alocacao.sala.horario.local.bairro,
        'cidade': alocacao.sala.horario.local.cidade,
        'chave': alocacao.candidato.chave,
    }

    mensagem = get_template('mail_alocacao.html').render(dados)

    msg = EmailMessage(
        'Local e horário de prova',
        mensagem,
        'Escola de Auxiliares e Técnicos de Enfermagem Nossa Senhora de Fátima - Inscrição <inscricao@sme.novafriburgo.rj.gov.br>',
#        ['loyola@sme.novafriburgo.rj.gov.br'],
#        ['loyola@sme.novafriburgo.rj.gov.br', 'eenfermagemnsf@sme.novafriburgo.rj.gov.br'],
        [alocacao.candidato.email],
    )
    msg.content_subtype = "html"  # Main content is now text/html
    msg.send()

    messages.error(request, 'E-Mail enviado.')

    return redirect('adm:envia_email')


@login_required
def relacao_candidatos(request):

    alocacoes = Alocacao.objects.all().order_by('candidato__nome')

    return render(request, "adm/relacao_candidatos.html",{"alocacoes" : alocacoes})


@login_required
def relacao_candidatos_assinatura(request):

    alocacoes = Alocacao.objects.all().order_by('candidato__nome')

    return render(request, "adm/relacao_candidatos_assinatura.html",{"alocacoes" : alocacoes})


@login_required
def relacao_candidatos_porta(request):

    alocacoes = Alocacao.objects.all().order_by('candidato__nome')

    return render(request, "adm/relacao_candidatos_porta.html",{"alocacoes" : alocacoes})

adm/templates/adm/busca_nome.html
{% extends "adm/cab.html" %}

{% load static %}

{% block cab %}
<br>
<div class="container">

    <div class="row">
        <div class="col-10">
            <h3>Envia E-Mail:</h3>
        </div>
    </div>

    <form method="POST" class="post-form" name="form">
        {% csrf_token %}
        <table  class="table table-striped table-bordered">
            {{ form.as_table }}
        </table>

        <input class="btn btn-primary" type="submit" value="Pesquisar">
    </form>


</div>

{% endblock %}

adm/templates/adm/cab.html
{% extends "adm/header.html" %}

{% load static %}

{% block header %}

    <div class="row">
        <div class="col-10">
            <h3>Escola Técnica de Auxiliar de Enfermagem</h3>
            <h3 class="display-6 text-bold text-md-left mb-1">Prefeitura Municipal de Nova Friburgo</h3>
            <h5 class="display-8 text-bold text-md-left mb-1">Secretaria de Ciência, Tecnologia, Inovação e Educação Profissionalizante e Superior</h5>
        </div>
        <div class="col">
            {% if user.is_authenticated %}Usuário: {{ user.username }}{% else %}{% endif %}
        </div>
    </div>

    <a href="{% url 'adm:inicio' %}" class="btn btn-primary" role="button">
        Início
    </a>

    <a href="{% url 'adm:sair' %}" class="btn btn-danger" role="button">
        Sair
    </a>
    <br>

    {% block cab %}{% endblock %}

{% endblock %}

adm/templates/adm/envia_email.html
{% extends "adm/cab.html" %}

{% load static %}

{% block cab %}
<br>
<div class="container">

    <div class="row">
        <div class="col-10">
            <h3>Envia E-Mail:</h3>
        </div>
    </div>

    <table  class="table table-striped table-bordered">

        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>CPF</th>
            </tr>
        </thead>

        {% for candidato in candidatos %}

            <tr>
            <td><a href="{% url 'adm:envia' candidato.id %}">{{ candidato.id }}</a></td>
            <td>{{ candidato.nome }}</td>
            <td>{{ candidato.cpf }}</td>
            </tr>

        {% endfor %}

    </table>
</div>

{% endblock %}

adm/templates/adm/header.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <link href="{% static 'css/jlb.css' %}" rel="stylesheet" type="text/css">

        <title>Técnico em Enfermagem</title>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>

    <SCRIPT LANGUAGE="JavaScript">
        {% if messages %}
            {% for message in messages %}
                alert("{{ message }}");
            {% endfor %}
        {% endif %}
    </script>

    <body class="body">
        <div class="container">

            {% block header %}{% endblock %}

        </div>

        <!-- JavaScript (Opcional) -->
        <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

adm/templates/adm/inicio.html
{% extends "adm/cab.html" %}

{% load static %}

{% block cab %}
<br>
<div class="container">

    <div class="row">
        <div class="col">
            <h3>Início:</h3>
        </div>
    </div>
    <ul>
    <li><a href="{% url 'adm:envia_email' %}">Envia e-mail</a></li>
    <li><a href="{% url 'adm:relacao_candidatos' %}" target="_blank">Imprime relação de candidatos (Dados completos)</a></li>
    <li><a href="{% url 'adm:relacao_candidatos_assinatura' %}" target="_blank">Imprime relação de candidatos (para assinatura)</a></li>
    <li><a href="{% url 'adm:relacao_candidatos_porta' %}" target="_blank">Imprime relação de candidatos (para afixar nas salas)</a></li>
    </ul>
    <br>

</div>

{% endblock %}

adm/templates/adm/relacao_candidatos.html
{% load template_filters %}

{% load static %}

<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <link href="{% static 'css/jlb.css' %}" rel="stylesheet" type="text/css">

        <title>Técnico em Enfermagem</title>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>

    <body class="body">
        <div class="container">

            <style type="text/css">

                .break { page-break-after: always; }

            </style>

            <br>
            <div class="container">

                {% for alocacao in alocacoes %}

                    {% ifchanged alocacao.sala.id %}
                        {%  if not forloop.first %}
                            </table>
                            <div class="break"></div>
                        {% endif %}

                        <div class="row">

                            <div class="col-5">
                                <img src="{% static "logo_prefeitura_transparente.png" %}" alt="Logo PMNF" title="Logo Cáritas"  style="margin:20px 0 0 15px;position: relative;left: 5px;" width="300px" />
                            </div>

                            <div class="col-7">
                                <h3 class="display-6 text-bold text-md-left mb-1">Secretaria Municipal de Educação</h3>
                                <h3 class="display-6 text-bold text-md-left mb-1">Escola Técnica de Auxiliar de Enfermagem</h3>
                                <h5 class="display-8 text-bold text-md-left mb-1">Secretaria Municipal de Ciência, Tecnologia, Inovação<br>e Educação Profissionalizante e Superior</h5>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-10">
                                <h3>Relação de candidatos:</h3>
                            </div>
                        </div>

                        <table  class="table table-striped table-bordered">
                    {% endifchanged %}


                    <tr>
                        <td>{{ alocacao.candidato.id }}</td>
                        <td>Nome: {{ alocacao.candidato.nome }}<br>E-Mail: {{ alocacao.candidato.email }}</td>
                        <td>CPF: {{ alocacao.candidato.cpf | formata_cpf }}<br>Celular: {{ alocacao.candidato.celular | formata_tel }}</td>
                        <td>Sala: {{ alocacao.sala.sala }}<br>Horário: {{ alocacao.sala.horario.horario }}</td>
                    </tr>

                {% endfor %}

                </table>

            </div>

            <SCRIPT LANGUAGE="JavaScript">
                window.print();
                setTimeout(function(){
                    window.close();
                },2000);
            </SCRIPT>

        </div>

        <!-- JavaScript (Opcional) -->
        <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

adm/templates/adm/relacao_candidatos_assinatura.html
{% load template_filters %}

{% load static %}

<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <link href="{% static 'css/jlb.css' %}" rel="stylesheet" type="text/css">

        <title>Técnico em Enfermagem</title>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>

    <body class="body">
        <div class="container">

            <style type="text/css">

                .break { page-break-after: always; }

            </style>

            <br>
            <div class="container">

                {% for alocacao in alocacoes %}

                    {% ifchanged alocacao.sala.id %}

                        {%  if not forloop.first %}
                            </table>
                            <div class="break"></div>
                        {% endif %}

                        <div class="row">

                            <div class="col-5">
                                <img src="{% static "logo_prefeitura_transparente.png" %}" alt="Logo PMNF" title="Logo Cáritas"  style="margin:20px 0 0 15px;position: relative;left: 5px;" width="300px" />
                            </div>

                            <div class="col-7">
                                <h3 class="display-6 text-bold text-md-left mb-1">Secretaria Municipal de Educação</h3>
                                <h3 class="display-6 text-bold text-md-left mb-1">Escola Técnica de Auxiliar de Enfermagem</h3>
                                <h5 class="display-8 text-bold text-md-left mb-1">Secretaria Municipal de Ciência, Tecnologia, Inovação<br>e Educação Profissionalizante e Superior</h5>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-10">
                                <h3>Relação de candidatos:</h3>
                            </div>
                        </div>

                        <table  class="table table-striped table-bordered">
                    {% endifchanged %}


                    <tr>
                        <td>{{ alocacao.candidato.id }}</td>
                        <td>Nome: {{ alocacao.candidato.nome }}<br>CPF:{{ alocacao.candidato.cpf | formata_cpf }}</td>
                        <td style="width:350px">Ass.:</td>
                        <td>Sala: {{ alocacao.sala.sala }}<br>Horário: {{ alocacao.sala.horario.horario }}</td>
                    </tr>

                {% endfor %}

                </table>

            </div>

            <SCRIPT LANGUAGE="JavaScript">
                window.print();
                setTimeout(function(){
                    window.close();
                },2000);
            </SCRIPT>

        </div>

        <!-- JavaScript (Opcional) -->
        <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

adm/templates/adm/relacao_candidatos_porta.html
{% load template_filters %}

{% load static %}

<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <link href="{% static 'css/jlb.css' %}" rel="stylesheet" type="text/css">

        <title>Técnico em Enfermagem</title>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>

    <body class="body">
        <div class="container">

            <style type="text/css">

                .break { page-break-after: always; }

            </style>

            <br>
            <div class="container">

                {% for alocacao in alocacoes %}

                    {% ifchanged alocacao.sala.id %}

                        {%  if not forloop.first %}
                            </table>
                            <div class="break"></div>
                        {% endif %}

                        <div class="row">

                            <div class="col-5">
                                <img src="{% static "logo_prefeitura_transparente.png" %}" alt="Logo PMNF" title="Logo Cáritas"  style="margin:20px 0 0 15px;position: relative;left: 5px;" width="300px" />
                            </div>

                            <div class="col-7">
                                <h3 class="display-6 text-bold text-md-left mb-1">Secretaria Municipal de Educação</h3>
                                <h3 class="display-6 text-bold text-md-left mb-1">Escola Técnica de Auxiliar de Enfermagem</h3>
                                <h5 class="display-8 text-bold text-md-left mb-1">Secretaria Municipal de Ciência, Tecnologia, Inovação<br>e Educação Profissionalizante e Superior</h5>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-10">
                                <h3>Relação de candidatos:</h3>
                            </div>
                        </div>

                        <table  class="table table-striped table-bordered">
                    {% endifchanged %}


                    <tr>
                        <td>{{ alocacao.candidato.id }}</td>
                        <td>Nome: {{ alocacao.candidato.nome }}</td>
                        <td>Sala: {{ alocacao.sala.sala }}<br>Horário: {{ alocacao.sala.horario.horario }}</td>
                    </tr>

                {% endfor %}

                </table>

            </div>

            <SCRIPT LANGUAGE="JavaScript">
                window.print();
                setTimeout(function(){
                    window.close();
                },2000);
            </SCRIPT>

        </div>

        <!-- JavaScript (Opcional) -->
        <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>